### ISSUE TITLE
[Bug] Can't use "type" command within shadow DOM

### ISSUE THREAD

**Issue by sangmai350** [abramenal/cypress-shadow-dom#1]
### Current behavior:
![Screenshot 2019-06-21 13 51 28](https://user-images.githubusercontent.com/37669424/59903690-d637da80-942b-11e9-86b8-b809a2223833.png)

### Desired behavior:
It should work

### Steps to reproduce: (app code and test code)
![Screenshot 2019-06-21 13 51 11](https://user-images.githubusercontent.com/37669424/59903730-ef408b80-942b-11e9-9648-3def90df39c5.png)
![Screenshot 2019-06-21 13 50 52](https://user-images.githubusercontent.com/37669424/59903738-f36ca900-942b-11e9-9843-7ff47a2e5d98.png)
![Screenshot 2019-06-21 13 50 41](https://user-images.githubusercontent.com/37669424/59903747-f9628a00-942b-11e9-8703-cd94dddc842b.png)

***We have an iframe that contain shadow dom. And we want to get element inside that iframe to handle, but not working at current. 

### Versions
cypress: 3.3.1

**Comment by abramenal** [comment]
HI @sangmai350 
Thanks for submitting the first issue!

I believe the code you wrote is not quite correct as you're using regular cypress commands for lookup.
I believe it should look somehow like:
```
cy.shadowGet('iframe body .input .wrp input').type(''123123);
```
you can also try like 
```
cy.shadowGet('iframe body .input .wrp input')
  .then($el => cy.wrap($el).type(''123123));
```

Please keep in mind if you have nested shadow elements, all of their selectors must appear in query for `shadowGet` – otherwise it'll be unable to get to their shadow roots.

Also, it might happen that `cy.type` command works with only elements attached to real DOM – in that case we'll need to implement a tiny custom command to support that. I would expect that case, but first need to ensure it's really needed, so please check that code example above and let me know if that works.

UPD: Alternative I thought about just letting cypress base commands to work not only with attached DOM elements, but that either may bring extra set of documentation about that or generally inconsistency (as not all the commands might be switched).

**Comment by sangmai350** [comment]
![Screenshot 2019-06-21 16 55 12](https://user-images.githubusercontent.com/37669424/59915043-ebb9fe00-9445-11e9-8688-a367552e998b.png)
 
Curently error that i got when try to replicate your comments. Can you please take a look?

**Comment by abramenal** [comment]
@sangmai350 
Right,  totally forgot the context piece:
`cy.document().shadowGet`
so shadowGet works within the document context only (as per docs)

**Comment by abramenal** [comment]
And regarding `.type` command itself – it may appear that it'll work only with passing `force: true` option

**Comment by abramenal** [comment]
@all-contributtors add @sangmai350 for bug

**Comment by abramenal** [comment]
@all-contributors add @sangmai350 for bug
